name: Daily Price Scraper

on:
  schedule:
    - cron: "0 5 * * *" # Runs every day at 05:00 UTC
  workflow_dispatch: # Allows manual triggering too

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install Playwright Browsers
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python priceComparison.py
