name: Daily Price Scraper

on:
  schedule:
    - cron: "0 5 * * *" # Runs every day at 05:00 UTC
  workflow_dispatch: # Allows manual triggering too

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install Playwright Browsers
        run: playwright install chromium

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python priceComparison.py

      - name: Commit updated CSV
        run: |
          git config user.name "KancerEzeroglu"
          git config user.email "ezeroglukancer@gmail.com"
          git add supermarket_prices.csv
          git commit -m "Update price data [auto]" || echo "No changes to commit"
          git push
