name: Daily Price Scraper

on:
  schedule:
    - cron: "0 5 * * *" # Runs every day at 05:00 UTC
  workflow_dispatch: # Allows manual triggering too

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install Playwright Browsers
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python priceComparison.py
      
      - name: Generate static HTML from CSV
        run: python generateHtml.py

      - name: Commit & Push
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "ezeroglukancer@gmail.com"
          git config --global user.name "KancerEzeroglu"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add docs/index.html supermarket_prices.csv
          git commit -m "📦 Daily update: scrape and HTML generated" || echo "No changes to commit"
          git push origin main
