name: Daily Price Scraper

on:
  schedule:
    - cron: "0 5 * * *" # Runs every day at 05:00 UTC
  workflow_dispatch: # Allows manual triggering too

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install Playwright Browsers
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python priceComparison.py
      
      - name: Generate static HTML from CSV
        run: python generateHtml.py

      - name: Commit and Push CSV + HTML
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git commit -m "📦 Daily update: scrape and HTML generated" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
